server:
  port: 8080

resilience4j.retry:
  configs:
    default:
      maxAttempts: 3
      waitDuration: 1000
      retryExceptions:
        - me.ramos.resilience4j.exception.RetryException
      ignoreExceptions:
        - me.ramos.resilience4j.exception.IgnoreException
  instances:
    simpleRetryConfig:
      baseConfig: default

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowType: COUNT_BASED
      minimumNumberOfCalls: 7
      slidingWindowSize: 10
      waitDurationInOpenState: 10s

      failureRateThreshold: 40

      slowCallDurationThreshold: 3000
      slowCallRateThreshold: 60

      permittedNumberOfCallsInHalfOpenState: 5
      automaticTransitionFromOpenToHalfOpenEnabled: true

      eventConsumerBufferSize: 10

      recordExceptions:
        - me.ramos.resilience4j.exception.RecordException
      ignoreExceptions:
        - me.ramos.resilience4j.exception.IgnoreException
  instances:
    simpleCircuitBreakerConfig:
      baseConfig: default

management:
  endpoints.web.exposure.include: '*'
  endpoint.health.show-details: always
  health:
    diskSpace.enabled: false
    circuitbreakers.enabled: true
  metrics.distribution.percentiles-histogram:
    http.server.requests: true
    resilience4j.circuitbreaker.calls: true
